### ISSUE TITLE
version mismatch between `nix run` and NixOS installation

### ISSUE THREAD

**Issue by bartoszluka** [nix-community/kickstart-nix.nvim#29] opened 2024-06-08 11:58 UTC
I want the installed Neovim to be the same as the flake one (version 0.10)

If I run `nvim --version` after adding an overlay to my NixOS config, I get
```
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/vchi0gkfmbx2bn1n4cyd5pjmp8f76s7y-neovim-unwrapped-0.9.5/share/nvim
"
```

but when I go to the directory where I configure kickstart-nix.nvim and do `nix run . -- --V1 -v` I get
```
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1693350652

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/vzncwh2bsj3a5mhz53xzcp6ldaq2cbhf-neovim-unwrapped-0.10.0/share/nvim
"
```
I would like for both of them to point to the same path or atleast be the same version (0.10).

relevant links:
- [my kickstart-nix.nvim config](https://github.com/bartoszluka/nvim.nix)
- [my NixOS config](https://github.com/bartoszluka/nixos)

**Comment by mrcjkb** [comment] 2024-06-08 12:39
Hey :wave: 

This is a duplicate of https://github.com/nix-community/kickstart-nix.nvim/discussions/16, so I'll close this issue.
The issue occurs when you apply the overlay to an older instance of nixpkgs (not the one pinned with this repo).

I've just [pushed a fix](https://github.com/nix-community/kickstart-nix.nvim/commit/834ee1df089c425e74545cab9dcfacaeb8d219f3) that makes sure kickstart-nix.nvim defaults to using neovim-unwrapped from the pinned nixpkgs.

**Closed by mrcjkb** 2024-06-08 12:39 UTC

**Comment by bartoszluka** [comment] 2024-06-08 13:18
Thank you! it works now
